version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    #build: ../backend
    image: shlicha/foodgram_backend:v1
    restart: always
    volumes:
      - ../frontend/build://app/static/
      - static_value:/app/static/
      - media_value:/app/media/
      - ./data/:/app/data/
    depends_on:
      - db
    env_file:
      - ./.env
  frontend:
    #build:
    #  context: ../frontend
    #  dockerfile: Dockerfile
    image: shlicha/foodgram_fronend:v1
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - web
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web
      - frontend

volumes:
  db_value: 
  static_value:
  media_value:    
