# Generated by Django 3.2.19 on 2023-06-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_shoping_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=8, null=True, unique=True, verbose_name='Цвет тега'),
        ),
    ]
