# Generated by Django 3.2.19 on 2023-06-03 13:51

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_recipe_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 3, 16, 51, 31, 96578), verbose_name='Дата публикации'),
        ),
    ]
