# Generated by Django 3.2.19 on 2023-06-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_recipe_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_count',
            field=models.IntegerField(default=0),
        ),
    ]
