# Generated by Django 3.2.19 on 2023-06-05 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_recipe_recipe_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_count',
        ),
    ]
