# Generated by Django 3.2.19 on 2023-06-05 15:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0014_remove_recipe_recipe_count'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shoping_Cart',
            new_name='ShopingCart',
        ),
    ]
