# Generated by Django 3.2.19 on 2023-06-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20230606_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='count_add_favorite',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Количество добавление в избранное'),
        ),
    ]
