# Generated by Django 3.2.19 on 2023-06-15 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20230609_0156'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IngredientsImport',
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ('name',), 'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
    ]
